# Generated by Django 5.1 on 2024-09-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('badge_color', models.CharField(max_length=20)),
                ('initials', models.CharField(max_length=2)),
                ('register', models.CharField(max_length=1)),
                ('selected', models.BooleanField(default=False)),
            ],
        ),
    ]
