# Generated by Django 5.1 on 2024-09-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contact_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
