# Generated by Django 5.1 on 2024-09-17 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_username_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
    ]
