# Generated by Django 5.1 on 2024-09-17 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_name_user_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='name',
        ),
    ]
