# Generated by Django 5.1 on 2024-09-16 19:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30)),
                ('description', models.CharField(default='', max_length=100)),
                ('priority', models.CharField(choices=[('URGENT', 'urgent'), ('MEDIUM', 'medium'), ('LOW', 'low')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('TODO', 'Todo'), ('INPROGRESS', 'inProgress'), ('AWAITFEEDBACK', 'awaitFeedback'), ('DONE', 'done')], default='TODO', max_length=13)),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('category', models.CharField(max_length=20)),
                ('contacts', models.ManyToManyField(blank=True, to='contacts.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Subtask_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('checked', models.BooleanField(default=False)),
                ('rel_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskitem.taskitem')),
            ],
        ),
    ]
