# Generated by Django 5.1.1 on 2024-09-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0002_contact_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30)),
                ('description', models.CharField(default='', max_length=100)),
                ('priority', models.CharField(choices=[('URG', 'urgent'), ('MED', 'medium'), ('LOW', 'low')], default='MED', max_length=10)),
                ('status', models.CharField(choices=[('TODO', 'Todo'), ('INPROGRESS', 'inProgress'), ('AWAITFEEDBACK', 'awaitFeedback'), ('DONE', 'done')], default='TODO', max_length=13)),
                ('contacts', models.ManyToManyField(to='contacts.contact')),
            ],
        ),
    ]
