# Generated by Django 5.1 on 2024-09-16 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskitem', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subtask_item',
            new_name='SubtaskItem',
        ),
    ]
