# Generated by Django 5.1.1 on 2024-09-12 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_user'),
        ('taskitem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='contacts.contact'),
        ),
        migrations.CreateModel(
            name='Subtask_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('checked', models.BooleanField(default=False)),
                ('rel_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskitem.taskitem')),
            ],
        ),
    ]
