# Generated by Django 5.1.1 on 2024-09-15 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskitem', '0002_alter_taskitem_contacts_subtask_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskitem',
            name='category',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskitem',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='priority',
            field=models.CharField(choices=[('URGENT', 'urgent'), ('MEDIUM', 'medium'), ('LOW', 'low')], default='MEDIUM', max_length=10),
        ),
    ]
