# Generated by Django 5.1 on 2024-09-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskitem', '0002_rename_subtask_item_subtaskitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='category',
            field=models.CharField(choices=[('Technical Task', 'Technical Task'), ('User Story', 'User Story')], default=None, max_length=20),
        ),
    ]
