# Generated by Django 5.1 on 2024-09-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskitem', '0004_alter_subtaskitem_rel_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskitem',
            name='priority',
            field=models.CharField(choices=[('urgent', 'urgent'), ('medium', 'medium'), ('low', 'low')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='status',
            field=models.CharField(choices=[('toDo', 'toDo'), ('inProgress', 'inProgress'), ('awaitFeedback', 'awaitFeedback'), ('done', 'done')], default='toDo', max_length=13),
        ),
    ]
